services:
  - type: web
    name: stremio-smartsubs
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /manifest.json
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1